djangoTutorial/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

djangoTutorial/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('create/', views.article_create, name="create"),
    path('<slug>/', views.article_detail, name="detail"),
    path('', views.article_list, name="list")
]

djangoTutorial/djangoTutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', article_views.article_list)
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoTutorial/accounts/models.py
from django.db import models

# Create your models here.

djangoTutorial/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = RichTextUploadingField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100] + '...'

djangoTutorial/articles/forms.py
from django import forms
from .import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

djangoTutorial/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

djangoTutorial/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.


def article_list(request):
    articles = Article.objects.all().order_by('created')
    return render(request, "articles/article_list.html", {'articles': articles})


def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

djangoTutorial/djangoTutorial/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    return render(request, "homepage.html")


def about(request):
    return render(request, "about.html")

djangoTutorial/articles/templates/acticles/article_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Articles</title>
</head>

<body>
    Article list
</body>

</html>

djangoTutorial/templates/about.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About page</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
</head>

<body>
    <h1>about us</h1>
</body>

</html>

djangoTutorial/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Login</h1>
<form method="post" class="site-form" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {{ form }}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}

    <input type="submit" value="Login">
</form>
{% endblock %}

djangoTutorial/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Sign Up</h1>
<form method="post" class="site-form" action="/accounts/signup/">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Signup">
</form>
{% endblock %}

djangoTutorial/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
    <h1>Add new article</h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

djangoTutorial/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2 class="title text">{{ article.title }}</h2>
        <p class="createdby">Created by {{ article.author }}</p>
        <img src="{{ article.thumb.url }}" alt="thumb" class="w-100">
        <p>{{ article.body | safe }}</p>
        <p class="created">{{ article.created }}</p>
    </div>
</div>
{% endblock %}

djangoTutorial/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Blogs</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2><a class="title text" href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
        <p>{{ article.snippet | safe }}</p>
        <p class="created">{{ article.created }}</p>
        <p class="author">created by {{article.author.username}}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

djangoTutorial/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}" />

    <style>
        #logo {
            max-width: 200px;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        <header>
            <a href="{% url 'articles:list' %}"><img src="{% static 'django-logo.png' %}" alt="list" id="logo"></a>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" name="button">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login'%}" class="highlight">Login</a></li>
                    <li><a href="{% url 'accounts:signup'%}" class="highlight">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

djangoTutorial/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home page</title>
</head>

<body>
    <h1>This is homepage</h1>
    <p>Welcome to django tutorial</p>
</body>

</html>